# Generated by Django 4.2 on 2023-04-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True)),
                ('data', models.DateField()),
            ],
        ),
    ]
