# Generated by Django 4.2 on 2023-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_data_appointments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
