# Generated by Django 4.2 on 2023-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_appointments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('Account_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('Describe_company', models.CharField(blank=True, max_length=200)),
                ('hiring_for', models.CharField(blank=True, max_length=100)),
                ('follow', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('is_verfied', models.BooleanField(default=False)),
                ('is_follow', models.BooleanField(default=False)),
                ('is_follower', models.BooleanField(default=False)),
                ('is_block', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
